### ISSUE TITLE
Including chord triggers core.typed initialization error

### ISSUE THREAD

**Issue by JvJ** [jarohen/chord#48]
When trying to use core.typed, I get the following initialization error:

CompilerException java.io.FileNotFoundException: Could not locate cljs/env__init.class or cljs/env.clj on classpath., compiling:(cljs/jvm/tools/analyzer.clj:1:1)

I've fiddled with my project.clj file, and I by process of elimination, I determined that the error only occurs when I include a dependency to jarhohen/chord.

Do you know what is causing this?

**Comment by JvJ** [comment]
Update to this: including org.clojure/jvm.tools.analyzer in my dependencies resolves the issue.  Maybe this should be documented.

**Comment by jarohen** [comment]
Hi Kaylen, thanks for the issue report! Chord doesn't have a direct dependency on tools.analyzer, so I'd like to get to the bottom of what's causing this before putting a recommendation in the README.

@bronsa: any idea what could be causing this?

James

**Comment by Bronsa** [comment]
That error doesn't rever to `tools.analyzer` but to the `jvm.tools.analyzer` library, which is an older analyzer written by the core.typed author. Not really sure why it's getting pulled in, I'm guessing it's still used by the cljs port of core.typed?

**Comment by jarohen** [comment]
Thanks @Bronsa :)

@JvJ - could you attach the output of `lein deps :tree` before and after adding the Chord dependency?

Cheers!
