### ISSUE TITLE
WebSocket connection to 'ws://localhost:8080/streaming' failed: Invalid frame header

### ISSUE THREAD

**Issue by twashing** [jarohen/chord#49]
When making a websocket connection to my server, `chrod/client.cljs:35` is giving me the error mssage.

```
WebSocket connection to 'ws://localhost:8080/streaming' failed: Invalid frame header
```

What does this mean and how can I fix it? Thanks.

**Comment by jarohen** [comment]
Hi there, thanks for reporting :) that's not one I've seen before, I'm afraid - would it be possible to post the code around it on client- and server-side so that I can repro?

**Comment by twashing** [comment]
Hey James,

I tried to set something up for you. Check out [this branch](https://github.com/twashing/beatthemarket/tree/spike/chord). Ignore the current _*Usage*_ docs and go to http://localhost:8080/index.html, after running this.
```
lein repl
=> (require '[beatthemarket.shell :as sh])
=> (require 'cljs.build.api)     ;; compile cljs
=> (cljs.build.api/build "src"
                        {:main 'beatthemarket.client.core
                         :output-to "resources/public/js/main.js"
                         :output-dir "resources/public/js"
                         :asset-path "js"})
=> (sh/start-server)
```

Are you seeing the same error I'm seeing? And am I just using _*chord*_ incorrectly?

Thanks

**Comment by jarohen** [comment]
Hey, thanks for sending this through. I've managed to connect to your streaming handler using a Chrome extension (couldn't find index.html?) by changing the `app` definition to:

```clojure
(def app
  (handler/site
   (compojure/routes
     (GET "/"           req (index-handler req))
     (GET "/streaming"  req ((wrap-websocket-handler streaming-handler) req))
     (route/resources "/")
     (route/not-found "Page not found"))))
```

The `wrap-websocket-handler` call checks whether the incoming request is a websocket upgrade request and, if so, performs the handshake, and puts the `ws-channel` into the request map.

Could you check whether your client-side app works with this change?

Cheers!

James

**Comment by twashing** [comment]
Ahh yes, that seems to have done the trick.

Thanks so much James. This helps a lot.


Tim Washington
415.283.8889

**Comment by jarohen** [comment]
No worries :)
