### ISSUE TITLE
Server miss first message

### ISSUE THREAD

**Issue by roman-dowakin** [jarohen/chord#50]
Hey, James!

I catch error - 
When server get first web socket (after restart) and this message really fast one like:
```
socket.onopen = e => { socket.send("hi"); };
```
than server side miss it for some reason.

Sorry, I didn't spend time to investigate it. I didn't use ClojureScript for project, so I rewrite everything just with `http-kit` with plain `on-receive`.

Maybe you have a clue about it. If not, I'll spend some time this or next weekend.

**Comment by jarohen** [comment]
Hi Roman - thanks for the report. I've not seen anything like this I'm afraid - did you have any luck with it?

Failing that, could you post the example and I can take a look?

Cheers,

James

**Comment by roman-dowakin** [comment]
Hey, James!

Tried to reproduce it in simple app, but everything seems working.
Don't have any clue why it happens. Maybe I did something wrong on serverside.

So I gonna close issue.

Thanks

**Comment by jarohen** [comment]
Hi Roman, thanks for letting me know! 

James
