### ISSUE TITLE
Serializing large message fails with {:format :edn}

### ISSUE THREAD

**Issue by aaronblenkush** [jarohen/chord#56]
Dispatching a large payload (~800KB) from websocket server using `{:format :edn}` results in `{:error :invalid-format}` on the `ws-channel` on the client side. I don't have this issue with a smaller payload.

I was able to work around this by changing to `{:format :transit-json}` on client and server.

**Comment by jarohen** [comment]
Hi Aaron, thanks for submitting the issue!

I'm afraid I haven't been repro that here as yet, do you have a small example case that you could post?

Cheers,

James
