### ISSUE TITLE
Getting this error ``ERR_DISALLOWED_URL_SCHEME``

### ISSUE THREAD

**Issue by VikramShawFL** [jarohen/chord#58]
So I have cloned your project and everything is same. When I run lein figwheel also it doesn't give me any error also and it runs perfectly on ``http://localhost:3449/`` but when I try to run on ``ws://localhost:3449/ws`` I'm getting this error
![image](https://user-images.githubusercontent.com/46559614/62352801-b1547e00-b526-11e9-9869-ffd4f28d5cd3.png)

**Comment by jarohen** [comment]
Hi there - could you give me an idea what you were expecting from that?

**Comment by VikramShawFL** [comment]
I was expecting a websocket chat app, where more than one user can chat when online

**Comment by jarohen** [comment]
Hey, that doesn't look much like the example chat app?

What I'm doing:
* Fresh git clone
* `cd example-project`
* `lein dev`, wait for it to start up
* Two browser windows, opening up http://localhost:3000
* Messages entered in one browser window are shown in the other

Could you let me know where your steps differ?

**Comment by jarohen** [comment]
![image](https://user-images.githubusercontent.com/336964/62495945-5c876080-b7cf-11e9-8c96-2b896e4dae64.png)

Here's what the Chord example app looks like, btw
